Document: hot-potato-router
Title: Debian hot-potato-router Manual
Author: <insert document author here>
Abstract: This manual describes what hot-potato-router is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hot-potato-router/hot-potato-router.sgml.gz

Format: postscript
Files: /usr/share/doc/hot-potato-router/hot-potato-router.ps.gz

Format: text
Files: /usr/share/doc/hot-potato-router/hot-potato-router.text.gz

Format: HTML
Index: /usr/share/doc/hot-potato-router/html/index.html
Files: /usr/share/doc/hot-potato-router/html/*.html
